PROMPT DROP TABLES;

DROP TABLE HAS CASCADE CONSTRAINT;
DROP TABLE PLACE CASCADE CONSTRAINT;
DROP TABLE BOOKING CASCADE CONSTRAINT;
DROP TABLE CUSTOMERS CASCADE CONSTRAINT;
DROP TABLE FLIGHTS CASCADE CONSTRAINT;

CREATE TABLE FLIGHTS (
    FLIGHT_NO	VARCHAR(5)  NOT NULL,
    SOURCE	VARCHAR(20),
    DEST	VARCHAR(20),
    DEPART_TIME DATE,
    ARRIVE_TIME DATE,
    FARE    INTEGER,
    SEAT_LIMIT  INTEGER,
    PRIMARY KEY (FLIGHT_NO)
    );

COMMIT;

PROMPT INSERT FLIGHTS TABLE;

INSERT INTO FLIGHTS VALUES('CX100', 'HK',   'Tokyo',    to_date('15/3/2025,12:00:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('15/3/2025,16:00:00', 'dd/mm/yyyy,hh24:mi:ss'), 2000,   3);
INSERT INTO FLIGHTS VALUES('CX101', 'Tokyo',    'New York', to_date('15/3/2025,18:30:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('15/3/2025,23:30:00', 'dd/mm/yyyy,hh24:mi:ss'), 4000,   3);
INSERT INTO FLIGHTS VALUES('CX102', 'HK',   'Beijing',  to_date('15/3/2025,10:00:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('15/3/2025,13:00:00', 'dd/mm/yyyy,hh24:mi:ss'), 2000, 1);
INSERT INTO FLIGHTS VALUES('CX103', 'Beijing',  'Tokyo',    to_date('15/3/2025,15:00:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('15/3/2025,18:00:00', 'dd/mm/yyyy,hh24:mi:ss'), 1500,   3);
INSERT INTO FLIGHTS VALUES('CX104', 'New York', 'Beijing',  to_date('15/3/2025,10:00:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('15/3/2025,14:00:00', 'dd/mm/yyyy,hh24:mi:ss'), 1500,   3);
INSERT INTO FLIGHTS VALUES('CX105', 'HK',   'New York', to_date('15/3/2025,04:00:00','dd/mm/yyyy,hh24:mi:ss'),  to_date('15/3/2025,09:00:00','dd/mm/yyyy,hh24:mi:ss'),  1000,   2);
INSERT INTO FLIGHTS VALUES('CX106', 'New York', 'LA',       to_date('15/3/2025,23:40:00', 'dd/mm/yyyy,hh24:mi:ss'), to_date('16/3/2025,03:00:00', 'dd/mm/yyyy,hh24:mi:ss'), 5000,   3);
INSERT INTO FLIGHTS VALUES('CX107', 'Beijing', 'Tokyo', to_date('15/3/2025,08:00:00','dd/mm/yyyy,hh24:mi:ss'),  to_date('15/3/2025,11:00:00','dd/mm/yyyy,hh24:mi:ss'),  1500,   3);

COMMIT;

PROMPT INSERT CUSTOMERS TABLE;

CREATE TABLE CUSTOMERS (
    CID VARCHAR(5),
    CNAME   VARCHAR(20),
    NATIONALITY VARCHAR(3),
    PASSPORT    VARCHAR(8),
    PRIMARY KEY (CID)
    );

COMMIT;

INSERT INTO CUSTOMERS VALUES('C01', 'Alice',    'CHN',  'P1234567');
INSERT INTO CUSTOMERS VALUES('C02', 'Bob',  'UK',   'P1111111');
INSERT INTO CUSTOMERS VALUES('C02', 'Cole', 'US',   'P7654321');

COMMIT;

PROMPT INSERT BOOKING TABLE AND ITS RELATIONSHIP;

CREATE TABLE BOOKING (
    BID VARCHAR(5),
    BFARE   INTEGER DEFAULT 0,
    PRIMARY KEY (BID)
    );

CREATE TABLE PLACE (
    BID VARCHAR(5)  NOT NULL,
    CID VARCHAR(5)  NOT NULL,
    PDATE DATE,
    PRIMARY KEY (BID, CID),
    FOREIGN KEY (BID) REFERENCES BOOKING (BID) ON DELETE CASCADE,
    FOREIGN KEY (CID) REFERENCES CUSTOMERS (CID) ON DELETE CASCADE
    );

CREATE TABLE HAS (
    BID VARCHAR(5)  NOT NULL,
    FLIGHT_NO VARCHAR(5)    NOT NULL,
    FSEQUENCE INTEGER,
    PRIMARY KEY (BID, FLIGHT_NO),
    FOREIGN KEY (BID) REFERENCES BOOKING (BID) ON DELETE CASCADE,
    FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHTS (FLIGHT_NO) ON DELETE CASCADE
    );

COMMIT;

PROMPT INSERT CONSTRAINTS;

CREATE OR REPLACE TRIGGER BOOKING_CREATE
AFTER INSERT ON HAS
FOR EACH ROW
DECLARE
    f   INTEGER;
BEGIN
    SELECT FARE INTO f FROM FLIGHTS WHERE FLIGHT_NO = :new.FLIGHT_NO;
    UPDATE BOOKING SET BFARE = BFARE + f WHERE BID = :new.BID;
    UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT - 1 WHERE FLIGHT_NO = :new.FLIGHT_NO;
END;
/

CREATE OR REPLACE TRIGGER BOOKING_CANCEL
AFTER DELETE ON HAS
FOR EACH ROW
BEGIN
    UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT + 1 WHERE FLIGHT_NO = :new.FLIGHT_NO;
END;
/

COMMIT;

CREATE OR REPLACE TRIGGER SEAT_LIMIT_constraint
BEFORE INSERT ON HAS
FOR EACH ROW
DECLARE
    l   INTEGER;
BEGIN
    SELECT SEAT_LIMIT INTO l FROM FLIGHTS WHERE FLIGHT_NO = :new.FLIGHT_NO;
    IF (l < 1) THEN
        DELETE FROM BOOKING WHERE BID = :new.BID;
        RAISE_APPLICATION_ERROR(-20000, 'Flight ' || :new.FLIGHT_NO || ' is fully booked! Booking terminated.');
    END IF;
END;
/

COMMIT;
