PROMPT DROP TABLES;

DROP TABLE FLIGHTS CASCADE CONSTRAINT;

DROP TABLE CUSTOMERS CASCADE CONSTRAINT;

DROP TABLE BOOKING CASCADE CONSTRAINT;

DROP TABLE PLACE CASCADE CONSTRAINT;

DROP TABLE HAS CASCADE CONSTRAINT;

DROP TRIGGER UPDATE_BOOKING_AND_FLIGHT;

DROP TRIGGER SEAT_LIMIT_constraint;